# Generated by Django 3.1.6 on 2021-03-19 06:08

from django.db import migrations, models
import filesapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0002_auto_20210319_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=filesapp.models.generate_post_name, width_field='width_field'),
        ),
    ]
