# Generated by Django 3.1.6 on 2021-03-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0004_auto_20210319_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='images', width_field='image_width'),
        ),
    ]
