# Generated by Django 3.1.7 on 2021-03-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0016_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='discription',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
