# Generated by Django 3.1.7 on 2021-03-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0018_image_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
    ]
