# Generated by Django 3.1.7 on 2021-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0022_remove_download_total_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='total_downloads',
            field=models.IntegerField(default=0),
        ),
    ]
