# Generated by Django 3.1.7 on 2021-03-29 08:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0023_download_total_downloads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='download',
            name='total_downloads',
        ),
        migrations.AddField(
            model_name='download',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='image',
            name='total_downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='download',
            name='po',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='download', to='filesapp.image'),
        ),
    ]
