# Generated by Django 3.1.2 on 2021-03-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesapp', '0026_like_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='author',
        ),
    ]
